import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  page: {
    colorScheme: 'light',
    minHeight: '100vh',
    backgroundColor: '#ffffff',
    color: '#111111',
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: 1.5,
  },
  shell: {
    width: 'min(672px, calc(100% - 40px))',
    marginInline: 'auto',
    paddingBlock: '80px 96px',
  },
  brandMark: {
    display: 'block',
    width: '36px',
    height: '36px',
    color: '#f1122a',
  },
  brandLine: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '10px',
    margin: '14px 0 0',
    fontSize: '15px',
    fontWeight: 500,
    lineHeight: 1.25,
  },
  version: {
    color: '#888888',
    fontWeight: 400,
  },
  introTitle: {
    margin: '21.75px 0 0',
    color: '#111111',
    fontSize: '15px',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: 1.25,
  },
  introText: {
    margin: '8px 0 0',
    color: '#888888',
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: 1.625,
  },
  featureSection: {
    marginTop: '56px',
  },
  sectionTitle: {
    margin: 0,
    color: '#111111',
    fontSize: '15px',
    fontWeight: 500,
    lineHeight: 1.5,
  },
  featureList: {
    display: 'grid',
    gap: '8px',
    margin: '16px 0 0',
    padding: 0,
    listStyle: 'none',
  },
  feature: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '4px',
    minHeight: '22.5px',
    color: '#111111',
    fontSize: '15px',
    lineHeight: 1.5,
  },
  featureIcon: {
    display: 'block',
    flex: '0 0 16px',
    width: '16px',
    height: '16px',
    marginTop: '3.25px',
    color: '#4b4b4b',
  },
  featureName: {
    color: '#111111',
    fontWeight: 500,
  },
  featureText: {
    margin: 0,
  },
  featureDescription: {
    color: '#888888',
  },
  howSection: {
    marginTop: '56px',
  },
  setupList: {
    display: 'grid',
    gap: '40px',
    margin: '16px 0 0',
    paddingInlineStart: '24px',
  },
  setupStep: {
    minWidth: 0,
    paddingInlineStart: '8px',
  },
  stepTitle: {
    margin: 0,
    color: '#111111',
    fontSize: '15px',
    fontWeight: 500,
    lineHeight: 1.5,
  },
  stepText: {
    margin: '8px 0 0',
    color: '#888888',
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: 1.625,
  },
  stepNote: {
    margin: '12px 0 0',
    paddingInlineStart: '12px',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: '#dddddd',
    color: '#666666',
    fontSize: '13px',
    lineHeight: 1.5,
  },
  snippetList: {
    display: 'grid',
    gap: '12px',
    minWidth: 0,
    marginTop: '16px',
  },
  codeExample: {
    minWidth: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    backgroundColor: '#ffffff',
  },
  codeHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    minWidth: 0,
    padding: '10px 12px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#eeeeee',
  },
  codeLabel: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    gap: '6px',
    minWidth: 0,
  },
  codeFilename: {
    overflow: 'hidden',
    color: '#111111',
    fontSize: '13px',
    fontWeight: 500,
    lineHeight: 1.5,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  codeLanguage: {
    color: '#888888',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 1.5,
  },
  copyButton: {
    flex: '0 0 auto',
    minHeight: '30px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#dddddd',
    borderRadius: 0,
    padding: '5px 9px',
    backgroundColor: '#ffffff',
    color: '#111111',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: '13px',
    fontWeight: 400,
    lineHeight: 1.25,
  },
  codeBlock: {
    maxWidth: '100%',
    minWidth: 0,
    margin: 0,
    overflowX: 'auto',
    padding: '14px 12px',
    color: '#3f3f3f',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: '12px',
    lineHeight: 1.55,
    whiteSpace: 'pre',
  },
  code: {
    display: 'block',
  },
  copyFeedback: {
    margin: '0 12px 12px',
    fontSize: '13px',
    lineHeight: 1.5,
  },
  copyFeedbackSuccess: {
    color: '#3f3f3f',
  },
  copyFeedbackFailure: {
    color: '#8a3030',
  },
});
