import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  page: {
    colorScheme: 'light',
    minHeight: '100vh',
    backgroundColor: '#ffffff',
    color: '#111111',
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: 1.5,
  },
  shell: {
    width: 'min(672px, calc(100% - 40px))',
    marginInline: 'auto',
    paddingBlock: '80px 96px',
  },
  brandMark: {
    display: 'block',
    width: '36px',
    height: '36px',
    color: '#f1122a',
  },
  brandLine: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '10px',
    margin: '14px 0 0',
    fontSize: '15px',
    fontWeight: 500,
    lineHeight: 1.25,
  },
  version: {
    color: '#888888',
    fontWeight: 400,
  },
  introTitle: {
    margin: '21.75px 0 0',
    color: '#111111',
    fontSize: '15px',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: 1.25,
  },
  introText: {
    margin: '8px 0 0',
    color: '#888888',
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: 1.625,
  },
  featureSection: {
    marginTop: '56px',
  },
  sectionTitle: {
    margin: 0,
    color: '#111111',
    fontSize: '15px',
    fontWeight: 500,
    lineHeight: 1.5,
  },
  featureList: {
    display: 'grid',
    gap: '8px',
    margin: '16px 0 0',
    padding: 0,
    listStyle: 'none',
  },
  feature: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '4px',
    minHeight: '22.5px',
    color: '#111111',
    fontSize: '15px',
    lineHeight: 1.5,
  },
  featureIcon: {
    display: 'block',
    flex: '0 0 16px',
    width: '16px',
    height: '16px',
    marginTop: '3.25px',
    color: '#4b4b4b',
  },
  featureName: {
    color: '#111111',
    fontWeight: 500,
  },
  featureText: {
    margin: 0,
  },
  featureDescription: {
    color: '#888888',
  },
  howSection: {
    marginTop: '56px',
  },
  howCards: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '16px',
    marginTop: '16.375px',
  },
  howCard: {
    display: 'flex',
    minHeight: '200px',
    flexDirection: 'column',
    padding: '24px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    backgroundColor: '#ffffff',
  },
  cardIcon: {
    display: 'block',
    width: '24px',
    height: '24px',
    color: '#111111',
  },
  cardTitle: {
    margin: '16px 0 0',
    color: '#111111',
    fontSize: '15px',
    fontWeight: 500,
    lineHeight: 1.5,
  },
  cardText: {
    margin: '7px 0 0',
    color: '#888888',
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: 1.5,
  },
  cardLink: {
    display: 'inline-flex',
    width: 'fit-content',
    marginTop: 'auto',
    paddingTop: '15px',
    color: '#111111',
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: 1.5,
    textDecoration: 'none',
  },
  setupCode: {
    margin: 'auto 0 0',
    overflowX: 'auto',
    paddingTop: '13px',
    color: '#3f3f3f',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: '10px',
    lineHeight: 1.45,
    whiteSpace: 'pre-wrap',
  },
  playgroundSection: {
    marginTop: '56px',
  },
  playgroundLead: {
    margin: '8px 0 0',
    color: '#888888',
    fontSize: '15px',
    lineHeight: 1.625,
  },
  playground: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '24px',
    marginTop: '16px',
    padding: '24px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    backgroundColor: '#ffffff',
  },
  playgroundLabel: {
    margin: 0,
    color: '#888888',
    fontSize: '13px',
    lineHeight: 1.5,
  },
  playgroundValue: {
    display: 'block',
    marginTop: '4px',
    color: '#111111',
    fontSize: '32px',
    fontWeight: 400,
    letterSpacing: '-0.04em',
    lineHeight: 1,
  },
  playgroundControls: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: '8px',
  },
  playgroundButton: {
    minWidth: '40px',
    minHeight: '36px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#111111',
    borderRadius: 0,
    paddingInline: '11px',
    backgroundColor: '#111111',
    color: '#ffffff',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: 1,
  },
  playgroundButtonSecondary: {
    borderColor: '#dddddd',
    backgroundColor: '#ffffff',
    color: '#111111',
  },
  playgroundHint: {
    gridColumn: '1 / -1',
    margin: 0,
    color: '#888888',
    fontSize: '13px',
    lineHeight: 1.5,
  },
});
